CREATE DATABASE GOODIES_SHOP;
USE GOODIES_SHOP;

	-- CUTOMERS TABLE
CREATE TABLE CUSTOMERS (
	CUSTOMER_ID INT PRIMARY KEY auto_increment,
    NAME VARCHAR (100),
    EMAIL VARCHAR (100) unique,
    CITY VARCHAR (50),
    SIGN_UP_DATE DATE
);


	-- PRODUCTS TABLE
CREATE TABLE PRODUCTS (
	PRODUCT_ID INT PRIMARY KEY AUTO_INCREMENT,
    PRODUCT_NAME VARCHAR(100),
    CATEGORY VARCHAR(100),
    PRICE DECIMAL(10,2),
    STOCK INT
);

	-- ORDERS TABLE
CREATE TABLE ORDERS (
	ORDER_ID INT PRIMARY KEY auto_increment,
    CUSTOMER_ID INT,
    ORDER_DATE DATE,
    ORDER_STATUS VARCHAR (100),
    
    CONSTRAINT FK_ORDERS_CUSTOMERS
    FOREIGN KEY (CUSTOMER_ID)
    REFERENCES CUSTOMERS (CUSTOMER_ID)
);

	-- ORDERS ITEMS TABLE
CREATE TABLE ORDER_ITEMS (
	ORDER_ITEM_ID INT PRIMARY KEY auto_increment,
    ORDER_ID INT,
    PRODUCT_ID INT,
    QUANTITY int,
    
    CONSTRAINT FK_ORDER_ITEMS_ORDERS
    FOREIGN KEY (ORDER_ID)
    REFERENCES ORDERS (ORDER_ID),
    
    CONSTRAINT FK_ORDERS_ITEMS_PRODUCT
    FOREIGN KEY (PRODUCT_ID)
    REFERENCES PRODUCTS (PRODUCT_ID)
);

	-- PAYMENTS TABLE
CREATE TABLE PAYMENTS (
	PAYMENT_ID INT PRIMARY KEY AUTO_INCREMENT,
    ORDER_ID INT,
    PAYMENT_MODE VARCHAR(100),
    AMOUNT DECIMAL (10,2),
    PAYMENT_DATE DATE,
    
    CONSTRAINT FK_PAYMENTS_ORDERS
    FOREIGN KEY (ORDER_ID)
    REFERENCES ORDERS (ORDER_ID)
);