
SHOW TRIGGERS LIKE 'CUSTOMERS';

	-- Prevent Negative Product Price
    
-- BEFORE INSERT
DELIMITER $$
CREATE TRIGGER PREVENT_NEGATIVE_PRICING_INSERT
BEFORE INSERT ON PRODUCTS
FOR EACH ROW				
BEGIN
		IF NEW.PRICE <= 0 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Price cannot be less than or equal to 0';
	END IF;
END $$
DELIMITER ;

-- BEFORE UPDATE
DELIMITER $$
CREATE TRIGGER PREVENT_NEGATIVE_PRICING_UPDATE
BEFORE UPDATE ON PRODUCTS
FOR EACH ROW				
BEGIN
		IF NEW.PRICE <= 0 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Price cannot be less than or equal to 0';
	END IF;
END $$
DELIMITER ;

	-- Prevent Negative Stock
    
-- BEFORE INSERT
DELIMITER ^^
CREATE TRIGGER PREVENT_NEGATIVE_STOCK_INSERT
BEFORE INSERT ON PRODUCTS
FOR EACH ROW				
BEGIN
		IF NEW.STOCK < 0 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'STOCK cannot be less than 0';
	END IF;
END ^^
DELIMITER ;

-- BEFORE UPDATE
DELIMITER ^^
CREATE TRIGGER PREVENT_NEGATIVE_STOCK_UPDATE
BEFORE UPDATE ON PRODUCTS
FOR EACH ROW				
BEGIN
		IF NEW.STOCK < 0 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'STOCK cannot be less than 0';
	END IF;
END ^^
DELIMITER ;

	-- Stock Availability Check

-- BEFORE INSERT
DELIMITER //
CREATE TRIGGER STOCK_AVAILABILTY_CHECK
BEFORE INSERT ON ORDER_ITEMS
FOR EACH ROW				
BEGIN
DECLARE available_stock INT;

		SELECT STOCK
		INTO available_stock
		FROM PRODUCTS
		WHERE PRODUCT_ID = NEW.PRODUCT_ID;
        
		IF NEW.QUANTITY > available_stock THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Requested quantity is not available in inventory';
	END IF;
END //
DELIMITER ; 

	/* Auto Reduce Inventory = Requirement:
	When an order item is successfully created, automatically decrease stock from the products table */
	
-- AFTER INSERT
DELIMITER //
CREATE TRIGGER AUTO_REDUCE_INVENTORY_INSERT
AFTER INSERT ON ORDER_ITEMS
FOR EACH ROW				
BEGIN
		UPDATE PRODUCTS 
        SET STOCK = STOCK - NEW.QUANTITY
        WHERE PRODUCT_ID = NEW.PRODUCT_ID;
END //
DELIMITER ;

-- AFTER UPDATE
DELIMITER //
CREATE TRIGGER AUTO_REDUCE_INVENTORY_UPDATE
AFTER UPDATE ON ORDER_ITEMS
FOR EACH ROW				
BEGIN
		UPDATE PRODUCTS 
        SET STOCK = STOCK - NEW.QUANTITY
        WHERE PRODUCT_ID = NEW.PRODUCT_ID;
END //
DELIMITER ;

	-- CHANGE IN PRICE
DELIMITER $$
CREATE TRIGGER product_price_CHANGE
AFTER UPDATE ON PRODUCTS
FOR EACH ROW				
BEGIN
		IF NEW.PRICE <> OLD.PRICE THEN
        INSERT INTO product_price_audit
        (PRODUCT_ID, OLD_PRICE, NEW_PRICE, CHANGE_DATE)
        VALUES
        (NEW.PRODUCT_ID, OLD.PRICE, NEW.PRICE, NOW());
	END IF;
END $$
DELIMITER ;


	-- If an order item is deleted (cancellation, correction, refund, etc.), inventory should be restored.
    
AFTER DELETE
DELIMITER //

CREATE TRIGGER AUTO_RESTORE_INVENTORY_DELETE
AFTER DELETE ON ORDER_ITEMS
FOR EACH ROW
BEGIN
    UPDATE PRODUCTS
    SET STOCK = STOCK + OLD.QUANTITY
    WHERE PRODUCT_ID = OLD.PRODUCT_ID;
END //

DELIMITER ;

	-- CUSTOMER AUDIT ENTRY AND EXIT

DELIMITER &&
CREATE TRIGGER CUSTOMERS_ENTRY_AUDIT
AFTER INSERT
ON CUSTOMERS
FOR EACH ROW
BEGIN
	INSERT INTO CUSTOMERS_ENTRY_EXIT
    (NEW_CUSTOMER_ID, NEW_NAME, NEW_EMAIL, NEW_CITY, SIGN_UP_DATE, MESSAGE)
    VALUES
    (NEW.CUSTOMER_ID, NEW.NAME, NEW.EMAIL, NEW.CITY, NEW.SIGN_UP_DATE, 'CUSTOMER SIGNED UP');
END &&
DELIMITER ;

DELIMITER &&
CREATE TRIGGER CUSTOMERS_EXIT_AUDIT
AFTER DELETE
ON CUSTOMERS
FOR EACH ROW
BEGIN
	INSERT INTO CUSTOMERS_ENTRY_EXIT
    (OLD_CUSTOMER_ID, OLD_NAME, OLD_EMAIL, OLD_CITY, SIGN_OUT_DATE, MESSAGE)
    VALUES
    (OLD.CUSTOMER_ID, OLD.NAME, OLD.EMAIL, OLD.CITY, NOW(), 'CUSTOMER SIGNED OUT');
END &&
DELIMITER ;