
	-- Product Price Audit
CREATE TABLE Product_Price_Audit (
	PRODUCT_AUDIT_ID INT PRIMARY KEY auto_increment,
    OLD_PRICE DECIMAL(10,2),
    NEW_PRICE DECIMAL(10,2),
    CHANGE_DATE DATETIME
);


CREATE TABLE CUSTOMERS_ENTRY_EXIT (
	CUSTOMER_AUDIT_IT INT PRIMARY KEY auto_increment,
	NEW_CUSTOMER_ID INT,
	OLD_CUSTOMER_ID INT,
    
    NEW_NAME VARCHAR(100),
    OLD_NAME VARCHAR(100),
    
    NEW_EMAIL VARCHAR(100),
    OLD_EMAIL VARCHAR(100),
    
    NEW_CITY VARCHAR(100),
    OLD_CITY VARCHAR(100),
    
    SIGN_UP_DATE DATETIME,
    SIGN_OUT_DATE DATETIME
);
