		-- ROLLUP - IT IS A EXTENSION TO GRUOP BY CLAUSE THAT IS UDED TO SUM UP THE COLUMN IN SUB AND GRAND TOTAL
        
USE GOODIES_SHOP;

SELECT
        IFNULL(C.NAME,'GRAND TOTAL') AS CUSTOMER_NAME,
        SUM(P.AMOUNT) AS TOTAL_SPEND
FROM CUSTOMERS C
JOIN ORDERS o ON O.CUSTOMER_ID = C.CUSTOMER_ID
JOIN PAYMENTS P ON P.ORDER_ID = O.ORDER_ID
GROUP BY C.NAME WITH ROLLUP
ORDER BY TOTAL_SPEND ASC;