
SELECT * FROM customers;
SELECT * FROM order_items;
SELECT * FROM orders;
SELECT * FROM payments;
SELECT * FROM products;
SELECT * FROM product_price_audit;

SELECT * FROM customers_entry_exit;
SELECT * FROM product_price_audit;

SELECT SUM(AMOUNT) AS TOTAL_REVENUE FROM PAYMENTS;

SELECT
		P.PRODUCT_NAME AS 'PRODUCT NAME',
        sum(P.PRICE * OT.QUANTITY) AS 'TOTAL SALE'
FROM PRODUCTS P
JOIN ORDER_ITEMS OT ON P.PRODUCT_ID = OT.PRODUCT_ID
JOIN ORDERS O ON O.ORDER_ID = OT.ORDER_ID
WHERE O.ORDER_STATUS = 'DELIVERED'
GROUP BY P.PRODUCT_NAME
ORDER BY `TOTAL SALE` DESC;

	-- SEARCH Top Customers by Spend
create view TOP_CUSTOMERS_BY_SPEND AS
SELECT
		C.CUSTOMER_ID AS CUSTOMER_ID,
        C.NAME AS CUSTOMER_NAME,
        SUM(P.AMOUNT) AS TOTAL_SPEND
FROM CUSTOMERS C
JOIN ORDERS o ON O.CUSTOMER_ID = C.CUSTOMER_ID
JOIN PAYMENTS P ON P.ORDER_ID = O.ORDER_ID
GROUP BY C.CUSTOMER_ID
ORDER BY TOTAL_SPEND desc;

SELECT * FROM TOP_CUSTOMERS_BY_SPEND;