
		-- COMMON TABLE EXPRESSION (CTE) : IT IS A TEMPORARY RESULT SET THAT EXISTS ONLY FOR THE DURATION FOR SINGLE SQL STATEMENTS.
        
WITH high_paid AS (
	SELECT
			EMPLOYEE_ID,
            FIRST_NAME,
            LAST_NAME,
            SALARY,
            dense_rank() OVER(ORDER BY SALARY DESC) AS SALARY_RANK
	FROM EMPLOYEES
)

SELECT *
FROM high_paid
WHERE SALARY > 70000;


WITH department_salary AS (
		SELECT
				DEPARTMENT_ID,
				SUM(SALARY) AS TOTAL_SALARY
			FROM EMPLOYEES
            GROUP BY DEPARTMENT_ID
) 

SELECT * FROM department_salary
WHERE TOTAL_SALARY > 150000;

-- Employees Above Department Average

WITH DPT_STATS AS 
( SELECT
		DEPARTMENT_ID AS 'Department',
		FIRST_NAME AS 'Employee Name',
        SALARY,
        AVG(SALARY) OVER(PARTITION BY DEPARTMENT_ID) AS DEPARTMENT_AVERAGE
FROM EMPLOYEES )

SELECT * FROM DPT_STATS
WHERE SALARY > DEPARTMENT_AVERAGE;
        


-- Highest Paid Employee in Each Department
WITH HIGH_EMP_PAID AS
(	SELECT EMPLOYEE_ID,
			FIRST_NAME,
            SALARY,
            ROW_NUMBER() OVER(ORDER BY SALARY DESC) AS SALARY_RANK
	FROM EMPLOYEES
)

SELECT * FROM HIGH_EMP_PAID
WHERE SALARY_RANK = 1;

