
		-- WINDOW FUNCTIONS = ITS PERFOEM CALCULATIONS ACROSS A SET OF ROWS THAT ARE RELATED TO CURRENT ROWS WITHOUT COLLAPSING TO THE ROWS.
        -- Unlike GROUP BY, it returns one result for every row.
        
-- Topic 1: ROW_NUMBER() = IT ASSIGN A UNIQUE SEQUENTIAL NUMBER TO EACH ROW BASED ON THE ORDER YOU SPECIFY.

SELECT 
		EMPLOYEE_ID,
        FIRST_NAME,
        LAST_NAME,
        DEPARTMENT_NAME,
        SALARY,
        ROW_NUMBER() OVER(PARTITION BY DEPARTMENT_NAME ORDER BY SALARY DESC) AS SALARY_RANK
	FROM EMPLOYEES E
    JOIN departments D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;