
		-- WINDOW FUNCTIONS = ITS PERFOEM CALCULATIONS ACROSS A SET OF ROWS THAT ARE RELATED TO CURRENT ROWS WITHOUT COLLAPSING TO THE ROWS.
        -- Unlike GROUP BY, it returns one result for every row.
        
-- Topic 1: ROW_NUMBER() = IT ASSIGN A UNIQUE SEQUENTIAL NUMBER TO EACH ROW BASED ON THE ORDER YOU SPECIFY.

	-- Display only the highest-paid employee from each department.
SELECT * FROM (
SELECT
		D.DEPARTMENT_NAME,
		E.EMPLOYEE_ID,
        E.FIRST_NAME,
        E.LAST_NAME,
        E.SALARY,
        ROW_NUMBER() OVER(PARTITION BY D.DEPARTMENT_NAME ORDER BY SALARY DESC) AS SALARY_RANK
	FROM EMPLOYEES E
    JOIN departments D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID ) AS QS
WHERE QS.SALARY_RANK <= 3;
    
	-- Number Employees by Hire Date
SELECT 
		EMPLOYEE_ID,
        FIRST_NAME,
        LAST_NAME,
        HIRE_DATE,
        RANK() OVER(ORDER BY HIRE_DATE ASC) AS HIRE_DATE_RANK
	FROM EMPLOYEES;
    
	-- Display every employee with a row number within each manager's team, ordered by hire date.
SELECT
		E1.EMPLOYEE_ID,
        E1.FIRST_NAME,
        E2.FIRST_NAME AS MANAGER_NAME,
        E1.HIRE_DATE,
        ROW_NUMBER() OVER(PARTITION BY  E1.MANAGER_ID ORDER BY HIRE_DATE DESC) AS RANK_HIRE_DATE
FROM EMPLOYEES E1
JOIN EMPLOYEES E2 ON E2.EMPLOYEE_ID = E1.MANAGER_ID;

SELECT
    DEPARTMENT_ID,
    EMPLOYEE_ID,
    FIRST_NAME,
    SALARY,
    LAG(SALARY) OVER(
        PARTITION BY DEPARTMENT_ID
        ORDER BY SALARY ASC
    ) AS PREVIOUS_SALARY,

    SALARY -
    LAG(SALARY) OVER(
        PARTITION BY DEPARTMENT_ID
        ORDER BY SALARY ASC
    ) AS DIFFERENCE_IN_SALARY

FROM EMPLOYEES;

SELECT
		DEPARTMENT_ID,
		FIRST_NAME,
        LAST_NAME,
        SALARY,
        LAG(SALARY) over(PARTITION BY DEPARTMENT_ID ORDER BY SALARY ASC) AS PREVIOUS_SALARY,
        CASE 
			WHEN SALARY = LAG(SALARY) over(PARTITION BY DEPARTMENT_ID ORDER BY SALARY ASC) THEN 'SALARY IS SAME AS PREVIOUS'
            WHEN SALARY > LAG(SALARY) over(PARTITION BY DEPARTMENT_ID ORDER BY SALARY ASC) THEN 'SALARY IS GREATER THEN PREVIOUS'
            WHEN SALARY < LAG(SALARY) over(PARTITION BY DEPARTMENT_ID ORDER BY SALARY ASC) THEN 'SALARY IS SMALLER THEN PREVIOUS'
            END AS RANK_PRV_SALARY,
		LEAD(SALARY) over(PARTITION BY DEPARTMENT_ID ORDER BY SALARY ASC) AS NEXT_SALARY,
        CASE
			WHEN SALARY = LEAD(SALARY) over(PARTITION BY DEPARTMENT_ID ORDER BY SALARY ASC) THEN 'SALARY IS SAME AS NEXT'
            WHEN SALARY > LEAD(SALARY) over(PARTITION BY DEPARTMENT_ID ORDER BY SALARY ASC) THEN 'SALARY IS GREATER THEN NEXT'
            WHEN SALARY < LEAD(SALARY) over(PARTITION BY DEPARTMENT_ID ORDER BY SALARY ASC) THEN 'SALARY IS SMALLER THEN NEXT'
            END AS RANK_NXT_SALARY
FROM EMPLOYEES;

-- Topic 5: FIRST_VALUE() = It returns the first value from the ordered window and repeats it for every row in that window.
-- 			LAST_VALUE() = So LAST_VALUE() only sees rows up to the current row, making the current row the "last" row in the frame.


-- FIRST_VALUE() usually works as expected because the first row is always within the default window frame.
-- LAST_VALUE() often requires an explicit window frame (ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) because the default frame ends at the current row.
SELECT 
		J.JOB_ID AS JOB_ID,
        J.JOB_TITLE AS JOB_TITLE,
        E.FIRST_NAME AS FIRST_NAME,
        E.LAST_NAME AS LAST_NAME,
        E.SALARY AS SALARY,
        FIRST_VALUE(SALARY) OVER(PARTITION BY J.JOB_ID ORDER BY E.SALARY DESC) AS HIGHEST_SALARY,
        LAST_VALUE(SALARY) OVER(PARTITION BY J.JOB_ID ORDER BY E.SALARY DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS LOWEST_SALARY,
        E.HIRE_DATE AS HIRE_DATE,
        FIRST_VALUE(HIRE_DATE) OVER(PARTITION BY J.JOB_ID ORDER BY E.HIRE_DATE DESC) AS HIGHEST_DATE,
        LAST_VALUE(HIRE_DATE) OVER(PARTITION BY J.JOB_ID ORDER BY E.HIRE_DATE DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS LOWEST_DATE
FROM EMPLOYEES E
JOIN JOBS J ON E.JOB_ID = J.JOB_ID;


-- Topic 6: NTILE() = Unlike the previous functions, NTILE() does not rank rows. It divides rows into groups (buckets).

SELECT
    DEPARTMENT_ID,
    FIRST_NAME,
    SALARY,
    NTILE(3) OVER(
        PARTITION BY DEPARTMENT_ID
        ORDER BY SALARY DESC
    ) AS SALARY_GROUP
FROM EMPLOYEES;


SELECT
		*,
		CASE
			WHEN S.CUSTOMERS_RANKING = 1 THEN 'Platinum'
			WHEN S.CUSTOMERS_RANKING = 2 THEN 'Gold'
			WHEN S.CUSTOMERS_RANKING = 3 THEN 'Silver'
			WHEN S.CUSTOMERS_RANKING = 4 THEN 'Bronze'
            
			END AS CUSTOMER_STATUS
FROM (
SELECT
		C.customer_id,
        C.customer_name,
        O.order_amount,
        NTILE(4) OVER W AS CUSTOMERS_RANKING
FROM CUSTOMERS C
JOIN ORDERS O ON C.customer_id = O.customer_id 
WINDOW W AS (ORDER BY O.order_amount DESC))AS S ;


-- NTH_VALUE() = Returns the Nth row from the window.

SELECT
    FIRST_NAME,
    SALARY,
    NTH_VALUE(SALARY,3)
    OVER(
        PARTITION BY DEPARTMENT_ID
        ORDER BY SALARY DESC
        ROWS BETWEEN UNBOUNDED PRECEDING
        AND UNBOUNDED FOLLOWING
    ) AS THIRD_HIGHEST
FROM EMPLOYEES;

-- PERCENT_RANK()

-- Returns the relative rank between 0 and 1.

-- Formula:

-- (rank - 1)
-- ------------
-- (total rows - 1)

SELECT
    EMPLOYEE_ID,
    FIRST_NAME,
    SALARY,
    PERCENT_RANK() OVER(
        ORDER BY SALARY DESC
    ) AS PERCENT_RANKING
FROM EMPLOYEES;

-- CUME_DIST()

-- Returns the cumulative distribution.

-- Formula

-- Rows ≤ Current Row
-- ------------------
-- Total Rows

SELECT
    EMPLOYEE_ID,
    FIRST_NAME,
    SALARY,
    CUME_DIST() OVER(
        ORDER BY SALARY DESC
    ) AS CUMULATIVE_DISTRIBUTION
FROM EMPLOYEES;